name = "subscription"
main = "src/index.ts"
compatibility_date = "2024-04-03"

# [vars]
# 已经在控制台设置：
# Template_link = "..."
# SUB_PATH = "..."

# [[kv_namespaces]]
# 已经在控制台设置：
# binding = "CONFIG_KV"
# id = "..."
